function applyHySCO(pe1_dir, pe2_dir, dwi1_dir, dwi2_dir, results_dir)

addpath(genpath('/home/xuagu37/spm12'));

[filename1, pe1, pe2] = return_file_name_pe(pe1_dir, pe2_dir);
pe1_new_dir = [results_dir, filename1,'_',pe1, '.nii'];
pe2_new_dir = [results_dir, filename1,'_',pe2, '.nii'];
[filename2, ~, ~] = return_file_name_pe(dwi1_dir, dwi2_dir);
dwi1_new_dir = [results_dir, filename2,'_',pe1, '.nii'];
dwi2_new_dir = [results_dir, filename2,'_',pe2, '.nii'];

dwi1_corrected_dir = [results_dir, filename2,'_',pe1, '_HySCO_corrected.nii.gz'];
dwi2_corrected_dir = [results_dir, filename2,'_',pe2, '_HySCO_corrected.nii.gz'];

if (contains(pe1, 'LR') || contains(pe2, 'LR'))
    line_5 = 'matlabbatch{1}.spm.tools.dti.prepro_choice.hysco_choice.hysco2.perm_dim = 1;';
    
elseif (contains(pe1, 'AP') || contains(pe2, 'AP'))
    line_5 = 'matlabbatch{1}.spm.tools.dti.prepro_choice.hysco_choice.hysco2.perm_dim = 2;';
    
end

% HySCO only takes .nii but not .nii.gz

system(['cp ', pe1_dir, ' ', results_dir]);
system(['cp ', pe2_dir, ' ', results_dir]);
system(['cp ', dwi1_dir, ' ', results_dir]);
system(['cp ', dwi2_dir, ' ', results_dir]);
system(['gunzip -f ' results_dir, filename1,'_',pe1, '.nii.gz']);
system(['gunzip -f ' results_dir, filename1,'_',pe2, '.nii.gz']);
system(['gunzip -f ' results_dir, filename2,'_',pe1, '.nii.gz']);
system(['gunzip -f ' results_dir, filename2,'_',pe2, '.nii.gz']);

line_1 = ['matlabbatch{1}.spm.tools.dti.prepro_choice.hysco_choice.hysco2.source_up = {''', pe2_new_dir, ',1''};'];
line_2 = ['matlabbatch{1}.spm.tools.dti.prepro_choice.hysco_choice.hysco2.source_dw = {''', pe1_new_dir, ',1''};'];
line_3 = ['matlabbatch{1}.spm.tools.dti.prepro_choice.hysco_choice.hysco2.others_up = {', newline, '''', dwi2_new_dir, ',1''',...
    newline, '''', dwi2_new_dir, ',2''',...
    newline, '''', dwi2_new_dir, ',3''',...
    newline, '''', dwi2_new_dir, ',4''',...
    newline, '''', dwi2_new_dir, ',5''',...
    newline, '''', dwi2_new_dir, ',6''',...
    newline, '''', dwi2_new_dir, ',7''',...
    newline, '''', dwi2_new_dir, ',8''',...
    newline, '''', dwi2_new_dir, ',9''',...
    newline, '''', dwi2_new_dir, ',10''',...
    newline, '''', dwi2_new_dir, ',11''',...
    newline, '''', dwi2_new_dir, ',12''',...
    newline, '''', dwi2_new_dir, ',13''',...
    newline, '''', dwi2_new_dir, ',14''',...
    newline, '''', dwi2_new_dir, ',15''',...
    newline, '''', dwi2_new_dir, ',16''',...
    newline, '''', dwi2_new_dir, ',17''',...
    newline, '''', dwi2_new_dir, ',18''',...
    newline, '''', dwi2_new_dir, ',19''',...
    newline, '''', dwi2_new_dir, ',20''',...
    newline, '''', dwi2_new_dir, ',21''',...
    newline, '''', dwi2_new_dir, ',22''',...
    newline, '''', dwi2_new_dir, ',23''',...
    newline, '''', dwi2_new_dir, ',24''',...
    newline, '};'];
line_4 = ['matlabbatch{1}.spm.tools.dti.prepro_choice.hysco_choice.hysco2.others_dw = {', newline, '''', dwi1_new_dir, ',1''',...
    newline, '''', dwi1_new_dir, ',2''',...
    newline, '''', dwi1_new_dir, ',3''',...
    newline, '''', dwi1_new_dir, ',4''',...
    newline, '''', dwi1_new_dir, ',5''',...
    newline, '''', dwi1_new_dir, ',6''',...
    newline, '''', dwi1_new_dir, ',7''',...
    newline, '''', dwi1_new_dir, ',8''',...
    newline, '''', dwi1_new_dir, ',9''',...
    newline, '''', dwi1_new_dir, ',10''',...
    newline, '''', dwi1_new_dir, ',11''',...
    newline, '''', dwi1_new_dir, ',12''',...
    newline, '''', dwi1_new_dir, ',13''',...
    newline, '''', dwi1_new_dir, ',14''',...
    newline, '''', dwi1_new_dir, ',15''',...
    newline, '''', dwi1_new_dir, ',16''',...
    newline, '''', dwi1_new_dir, ',17''',...
    newline, '''', dwi1_new_dir, ',18''',...
    newline, '''', dwi1_new_dir, ',19''',...
    newline, '''', dwi1_new_dir, ',20''',...
    newline, '''', dwi1_new_dir, ',21''',...
    newline, '''', dwi1_new_dir, ',22''',...
    newline, '''', dwi1_new_dir, ',23''',...
    newline, '''', dwi1_new_dir, ',24''',...
    newline, '};'];
line_6 = 'matlabbatch{1}.spm.tools.dti.prepro_choice.hysco_choice.hysco2.dummy_fast = 1;';
line_7 = 'matlabbatch{1}.spm.tools.dti.prepro_choice.hysco_choice.hysco2.dummy_ecc = 0;';
line_8 = 'matlabbatch{1}.spm.tools.dti.prepro_choice.hysco_choice.hysco2.alpha = 50;';
line_9 = 'matlabbatch{1}.spm.tools.dti.prepro_choice.hysco_choice.hysco2.beta = 10;';
line_10 = 'matlabbatch{1}.spm.tools.dti.prepro_choice.hysco_choice.hysco2.dummy_3dor4d = 0;';
line_11 = 'matlabbatch{1}.spm.tools.dti.prepro_choice.hysco_choice.hysco2.restrictdim = [1, 1, 1];';

fileID = fopen([results_dir, 'HySCO_job.m'],'w');
fprintf(fileID,'%s \n',line_1);
fprintf(fileID,'%s \n',line_2);
fprintf(fileID,'%s \n',line_3);
fprintf(fileID,'%s \n',line_4);
fprintf(fileID,'%s \n',line_5);
fprintf(fileID,'%s \n',line_6);
fprintf(fileID,'%s \n',line_7);
fprintf(fileID,'%s \n',line_8);
fprintf(fileID,'%s \n',line_9);
fprintf(fileID,'%s \n',line_10);
fprintf(fileID,'%s \n',line_11);
fclose(fileID);

nrun = 1; % enter the number of runs here
jobfile = {[results_dir, 'HySCO_job.m']};
jobs = repmat(jobfile, 1, nrun);
inputs = cell(0, nrun);
for crun = 1:nrun
end
spm('defaults', 'FMRI');
spm_jobman('run', jobs, inputs{:});

% average AP and PA results
temp1_dir = [results_dir, 'u2', filename2,'_',pe1, '.nii'];
temp2_dir = [results_dir, 'u2', filename2,'_',pe2, '.nii'];
system(['gzip ', temp1_dir]);
system(['gzip ', temp2_dir]);
system(['mv ', temp1_dir, '.gz ', dwi1_corrected_dir]);
system(['mv ', temp2_dir, '.gz ', dwi2_corrected_dir]);




end